# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Lint

on:
  push:
    branches: [ "development" ]
  pull_request:
    branches: [ "main" ]

jobs:

  lint:
    runs-on: [self-hosted, linux, x64]

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go 1.22.4
      uses: actions/setup-go@v5
      with:
        go-version: '1.22.4'

    - name: Install dependencies
      run: go get .

    - name: Run linter
      run: 
